---
{
   "kind": "pipeline",
   "name": "default",
   "services": [
      {
         "image": "kennethreitz/httpbin",
         "name": "httpbin"
      }
   ],
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install --yes locales",
            "echo \"en_US.UTF-8 UTF-8\" > /etc/locale.gen",
            "locale-gen"
         ],
         "image": "buildpack-deps:stable",
         "name": "install locales",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            }
         ]
      },
      {
         "commands": [
            "apt-get update",
            "apt-get install --yes curl sudo",
            "groupadd nixbld",
            "useradd --create-home --groups nixbld nixuser",
            "chown nixuser: /nix",
            "echo \"nixuser ALL=(ALL:ALL) NOPASSWD: ALL\" > /etc/sudoers.d/nixuser",
            "unset NIX_REMOTE",
            "curl -L https://nixos.org/nix/install | sh -s -- --no-daemon",
            ". $HOME/.nix-profile/etc/profile.d/nix.sh",
            "cat $HOME/.nix-profile/etc/profile.d/nix.sh",
            "echo $HOME",
            "echo $PATH",
            "nix-channel --update",
            "nix-env -i nix curl"
         ],
         "depends_on": [
            "install locales"
         ],
         "image": "buildpack-deps:stable",
         "name": "install nix",
         "volumes": [
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "ls /nix/var/nix/profiles/",
            "ls /nix/var/nix/profiles/per-user/",
            "{ find /nix/var/nix/profiles/ | grep profile.d ; } || true",
            "find /nix/var/nix/profiles/",
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell --run true shell.nix"
         ],
         "depends_on": [
            "install nix"
         ],
         "image": "buildpack-deps:stable",
         "name": "install ci deps",
         "volumes": [
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:24.5-ci-cask",
         "name": "test-emacs24.5",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:25.1-ci-cask",
         "name": "test-emacs25.1",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:25.2-ci-cask",
         "name": "test-emacs25.2",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:25.3-ci-cask",
         "name": "test-emacs25.3",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:26.1-ci-cask",
         "name": "test-emacs26.1",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:26.2-ci-cask",
         "name": "test-emacs26.2",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:26.3-ci-cask",
         "name": "test-emacs26.3",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "locales",
         "temp": { }
      },
      {
         "name": "nix",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "test for emacs 24.4",
   "services": [
      {
         "image": "kennethreitz/httpbin",
         "name": "httpbin"
      }
   ],
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install --yes locales",
            "locale-gen en_US.UTF-8"
         ],
         "image": "ubuntu:12.04",
         "name": "install locales",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            }
         ]
      },
      {
         "commands": [
            "apt-get update",
            "apt-get install --yes curl sudo",
            "groupadd nixbld",
            "useradd --create-home --groups nixbld nixuser",
            "chown nixuser: /nix",
            "echo \"nixuser ALL=(ALL:ALL) NOPASSWD: ALL\" > /etc/sudoers.d/nixuser",
            "unset NIX_REMOTE",
            "curl -L https://nixos.org/nix/install | sh -s -- --no-daemon",
            ". $HOME/.nix-profile/etc/profile.d/nix.sh",
            "cat $HOME/.nix-profile/etc/profile.d/nix.sh",
            "echo $HOME",
            "echo $PATH",
            "nix-channel --update",
            "nix-env -i nix curl"
         ],
         "depends_on": [
            "install locales"
         ],
         "image": "ubuntu:12.04",
         "name": "install nix",
         "volumes": [
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "ls /nix/var/nix/profiles/",
            "ls /nix/var/nix/profiles/per-user/",
            "{ find /nix/var/nix/profiles/ | grep profile.d ; } || true",
            "find /nix/var/nix/profiles/",
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell --run true shell.nix"
         ],
         "depends_on": [
            "install nix"
         ],
         "image": "ubuntu:12.04",
         "name": "install ci deps",
         "volumes": [
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      },
      {
         "commands": [
            "echo \"/nix/var/nix/profiles/per-user/nixuser/profile\"",
            "echo \"$HOME/.nix-profile\"",
            "ln -sf \"/nix/var/nix/profiles/per-user/nixuser/profile\" \"$HOME/.nix-profile\"",
            ". \"$HOME/.nix-profile/etc/profile.d/nix.sh\"",
            "unset NIX_REMOTE",
            "nix-shell shell.nix",
            "cask install",
            "sleep 15",
            "cask exec ert-runner"
         ],
         "depends_on": [
            "install ci deps"
         ],
         "environment": {
            "MB_URL_TEST__HTTPBIN_PREFIX": "http://httpbin"
         },
         "image": "silex/emacs:24.4-ci-cask",
         "name": "test-emacs24.4",
         "volumes": [
            {
               "name": "locales",
               "path": "/usr/lib/locale"
            },
            {
               "name": "nix",
               "path": "/nix"
            }
         ]
      }
   ],
   "volumes": [
      {
         "name": "locales",
         "temp": { }
      },
      {
         "name": "nix",
         "temp": { }
      }
   ]
}
...
